"""Build the GitHub Pages bundle (iPad / any browser, works offline after first visit).

Usage:
  python tools/build_pages.py --site DIR     build the static site only (used by the GitHub workflow)
  python tools/build_pages.py --source DIR   zip the repository sources into DIR/src.zip.partNN
                                             (bulk upload through the GitHub web UI; the workflow unpacks them)
  python tools/build_pages.py [output_dir]   legacy: zipped site parts for a bundle-only repository

Produces in output_dir (default: build/pages):
  site/                    the static site (dist/ + sw.js + .nojekyll), for inspection
  upload/site.zip.partNN   the site zipped and split into <9 MB parts (GitHub web upload)
  upload/.github/workflows/pages.yml   workflow that joins the parts, unzips and deploys

Only dist/ is published. tests/ (book captures) and node_modules/ are never included.
"""
import hashlib, json, os, shutil, sys, zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 and not sys.argv[1].startswith('--') else ROOT / 'build' / 'pages'
SKIP_DIRS = {'_diag'}
PART = 9 * 1024 * 1024

WORKFLOW = """name: Deploy SKCT app to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      # One-time (or bulk) import: src.zip.partNN uploaded through the web UI are unpacked
      # into the repository as ordinary files and the parts are removed.
      - name: Unpack uploaded source bundle
        run: |
          if ls src.zip.part* >/dev/null 2>&1; then
            cat src.zip.part* > /tmp/src.zip
            unzip -o -q /tmp/src.zip -d .
            git rm -q --ignore-unmatch src.zip.part* site.zip.part*
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -q -m "Unpack uploaded source bundle"
            git push
          fi
      - name: Build site (dist + offline cache list)
        run: python3 tools/build_pages.py --site _site
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
"""

SW = """// Offline cache for the SKCT practice app. Generated by tools/build_pages.py.
const VERSION = %(version)s;
const FILES = %(files)s;
const CACHE = 'skct-' + VERSION;
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Add in small groups so a slow connection does not fail the whole install.
    for (let i = 0; i < FILES.length; i += 12) await cache.addAll(FILES.slice(i, i + 12));
    await self.skipWaiting();
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith('skct-') && key !== CACHE) await caches.delete(key);
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const url = new URL(req.url); url.search = '';
    const hit = await cache.match(req.mode === 'navigate' ? new URL('./', self.registration.scope).href : url.href);
    if (hit) return hit;
    try { return await fetch(req); }
    catch { return (await cache.match(new URL('./', self.registration.scope).href)) || Response.error(); }
  })());
});
"""


def build_site(site):
    shutil.rmtree(site, ignore_errors=True)
    shutil.copytree(ROOT / 'dist', site, ignore=lambda d, names: [n for n in names if n in SKIP_DIRS])
    files, digest = [], hashlib.sha256()
    for p in sorted(site.rglob('*')):
        if p.is_file():
            rel = p.relative_to(site).as_posix()
            files.append(rel)
            digest.update(rel.encode()); digest.update(p.read_bytes())
    version = digest.hexdigest()[:12]
    precache = ['./'] + [f for f in files if f != 'index.html'] + ['index.html']
    (site / 'sw.js').write_text(SW % {'version': json.dumps(version), 'files': json.dumps(precache, ensure_ascii=False)}, encoding='utf-8')
    (site / '.nojekyll').write_text('')
    return version, files


def split(data, folder, name):
    folder.mkdir(parents=True, exist_ok=True)
    parts = [data[i:i + PART] for i in range(0, len(data), PART)]
    for i, chunk in enumerate(parts, 1):
        (folder / f'{name}.part{i:02d}').write_bytes(chunk)
    return len(parts)


# Repository sources. Book captures (tests/fixtures), caches and node_modules are never included.
SOURCE_FILES = ['README.md', 'QA.md', 'package.json', 'package-lock.json', 'server.mjs', 'START.cmd', 'STOP.cmd', 'launch.ps1', '.gitignore']
SOURCE_DIRS = ['dist', 'tools', 'tests']
SOURCE_SKIP = {'_diag', 'fixtures', '.ocr-cache', '__pycache__', 'node_modules'}
GITIGNORE = "node_modules/\ntests/fixtures/\ntests/.ocr-cache/\ndist/_diag/\nbuild/\n__pycache__/\n_site/\n"


def build_source(out):
    shutil.rmtree(out, ignore_errors=True); out.mkdir(parents=True)
    if not (ROOT / '.gitignore').exists():
        (ROOT / '.gitignore').write_text(GITIGNORE, encoding='utf-8')
    zpath = out / 'src.zip'
    count = 0
    with zipfile.ZipFile(zpath, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for name in SOURCE_FILES:
            if (ROOT / name).exists(): z.write(ROOT / name, name); count += 1
        for d in SOURCE_DIRS:
            for p in sorted((ROOT / d).rglob('*')):
                rel = p.relative_to(ROOT)
                if p.is_file() and not SOURCE_SKIP.intersection(rel.parts):
                    z.write(p, rel.as_posix()); count += 1
    data = zpath.read_bytes(); zpath.unlink()
    n = split(data, out, 'src.zip')
    (out / 'pages.yml').write_text(WORKFLOW, encoding='utf-8')
    print(f'{count} files, zip {len(data)/1048576:.1f} MB in {n} part(s) -> {out}')


def main():
    args = sys.argv[1:]
    if args[:1] == ['--site']:
        version, files = build_site(Path(args[1]))
        print(f'site version {version}: {len(files)} files -> {args[1]}')
        return
    if args[:1] == ['--source']:
        build_source(Path(args[1]) if len(args) > 1 else ROOT / 'build' / 'source')
        return
    site = OUT / 'site'
    upload = OUT / 'upload'
    shutil.rmtree(OUT, ignore_errors=True)
    version, files = build_site(site)
    zpath = OUT / 'site.zip'
    with zipfile.ZipFile(zpath, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in sorted(site.rglob('*')):
            if p.is_file():
                z.write(p, p.relative_to(site).as_posix())
    data = zpath.read_bytes(); zpath.unlink()
    n = split(data, upload, 'site.zip')
    wf = upload / '.github' / 'workflows'
    wf.mkdir(parents=True)
    (wf / 'pages.yml').write_text(WORKFLOW, encoding='utf-8')
    print(f'version {version}: {len(files)} files, zip {len(data)/1048576:.1f} MB in {n} part(s) -> {upload}')


if __name__ == '__main__':
    main()
